apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    app: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      type: back
  template:
    metadata:
       name: worker 
       labels:
         app: worker
         type: back
    spec:
      containers:
        - name: worker-app
          image: nelrajan/worker
