apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    app: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
      type: front
  template:
    metadata:
       name: vote 
       labels:
         app: vote
         type: front
    spec:
      containers:
        - name: voting-app
          image: nelrajan/vote
          ports:
            - containerPort: 80
